# in .cargo/config.toml

############ fake-os dev ############
# This is use for fake-os develop

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "testing/x86_64-bare-metal.json"
############ fake-os end ############
